# Generated by Django 4.2.3 on 2023-08-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Tax',
            field=models.IntegerField(null=True),
        ),
    ]
